---
  header_logo_url:  https://sfg.taxonworks.org/s/9dnt8d
  header_logo_text: Embioptera Species File
  header_links:
    - label: Home
      link: /

    - label: Search DwC
      link: /resources/tw/filter/dwc_otus

    - label: About
      link: /about
